
[[redirects]]
  from = "/comments"
  to = "https://my-life-visitor-state.windking566.workers.dev/comments"
  status = 200
  force = true

[[redirects]]
  from = "/presence"
  to = "https://my-life-visitor-state.windking566.workers.dev/presence"
  status = 200
  force = true

[[redirects]]
  from = "/online-count"
  to = "https://my-life-visitor-state.windking566.workers.dev/online-count"
  status = 200
  force = true

[[redirects]]
  from = "/visits"
  to = "https://my-life-visitor-state.windking566.workers.dev/visits"
  status = 200
  force = true

[[redirects]]
  from = "/admin-data"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-data"
  status = 200
  force = true

[[redirects]]
  from = "/admin-comments"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-comments"
  status = 200
  force = true

[[redirects]]
  from = "/admin-comments/:id"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-comments/:id"
  status = 200
  force = true

[[redirects]]
  from = "/admin-owner-ip-marks"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-owner-ip-marks"
  status = 200
  force = true

[[redirects]]
  from = "/admin-owner-ip-marks/:ipAddress"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-owner-ip-marks/:ipAddress"
  status = 200
  force = true

[[redirects]]
  from = "/admin-visits"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-visits"
  status = 200
  force = true

[[redirects]]
  from = "/2025/11/29/新的旅程/"
  to = "/2025/11/29/journey/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/11/29/%E6%96%B0%E7%9A%84%E6%97%85%E7%A8%8B/"
  to = "/2025/11/29/journey/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/11/30/我的生活/"
  to = "/2025/11/30/now/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/11/30/%E6%88%91%E7%9A%84%E7%94%9F%E6%B4%BB/"
  to = "/2025/11/30/now/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/11/30/记录一下/"
  to = "/2025/11/30/notes/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/11/30/%E8%AE%B0%E5%BD%95%E4%B8%80%E4%B8%8B/"
  to = "/2025/11/30/notes/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/11/30/长不大的少年/"
  to = "/2025/11/30/boy/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/11/30/%E9%95%BF%E4%B8%8D%E5%A4%A7%E7%9A%84%E5%B0%91%E5%B9%B4/"
  to = "/2025/11/30/boy/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/12/01/另一个博客/"
  to = "/2025/12/01/search/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/12/01/%E5%8F%A6%E4%B8%80%E4%B8%AA%E5%8D%9A%E5%AE%A2/"
  to = "/2025/12/01/search/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/12/14/越简单越复杂，越复杂越简单/"
  to = "/2025/12/14/year-end/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/12/14/%E8%B6%8A%E7%AE%80%E5%8D%95%E8%B6%8A%E5%A4%8D%E6%9D%82%EF%BC%8C%E8%B6%8A%E5%A4%8D%E6%9D%82%E8%B6%8A%E7%AE%80%E5%8D%95/"
  to = "/2025/12/14/year-end/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/12/18/蓝色夜晚的记忆/"
  to = "/2025/12/18/blue-night/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/12/18/%E8%93%9D%E8%89%B2%E5%A4%9C%E6%99%9A%E7%9A%84%E8%AE%B0%E5%BF%86/"
  to = "/2025/12/18/blue-night/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/12/21/马上要圣诞节咯/"
  to = "/2025/12/21/christmas/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/12/21/%E9%A9%AC%E4%B8%8A%E8%A6%81%E5%9C%A3%E8%AF%9E%E8%8A%82%E5%92%AF/"
  to = "/2025/12/21/christmas/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/01/14/一定要注意身体/"
  to = "/2026/01/14/health/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/01/14/%E4%B8%80%E5%AE%9A%E8%A6%81%E6%B3%A8%E6%84%8F%E8%BA%AB%E4%BD%93/"
  to = "/2026/01/14/health/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/02/06/你不必记录一切/"
  to = "/2026/02/06/let-go/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/02/06/%E4%BD%A0%E4%B8%8D%E5%BF%85%E8%AE%B0%E5%BD%95%E4%B8%80%E5%88%87/"
  to = "/2026/02/06/let-go/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/02/11/如何才算休息/"
  to = "/2026/02/11/rest/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/02/11/%E5%A6%82%E4%BD%95%E6%89%8D%E7%AE%97%E4%BC%91%E6%81%AF/"
  to = "/2026/02/11/rest/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/02/12/马上要放假了/"
  to = "/2026/02/12/holiday/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/02/12/%E9%A9%AC%E4%B8%8A%E8%A6%81%E6%94%BE%E5%81%87%E4%BA%86/"
  to = "/2026/02/12/holiday/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/05/16/天上的云一直在飘/"
  to = "/2026/05/16/clouds/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/05/16/%E5%A4%A9%E4%B8%8A%E7%9A%84%E4%BA%91%E4%B8%80%E7%9B%B4%E5%9C%A8%E9%A3%98/"
  to = "/2026/05/16/clouds/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/06/05/真假感情/"
  to = "/2026/06/05/feelings/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/06/05/%E7%9C%9F%E5%81%87%E6%84%9F%E6%83%85/"
  to = "/2026/06/05/feelings/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/06/08/蜕变了吗/"
  to = "/2026/06/08/change/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/06/08/%E8%9C%95%E5%8F%98%E4%BA%86%E5%90%97/"
  to = "/2026/06/08/change/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/06/22/风/"
  to = "/2026/06/22/wind/"
  status = 301
  force = true

[[redirects]]
  from = "/2026/06/22/%E9%A3%8E/"
  to = "/2026/06/22/wind/"
  status = 301
  force = true
