[[redirects]]
  from = "/comments"
  to = "https://my-life-visitor-state.windking566.workers.dev/comments"
  status = 200
  force = true

[[redirects]]
  from = "/presence"
  to = "https://my-life-visitor-state.windking566.workers.dev/presence"
  status = 200
  force = true

[[redirects]]
  from = "/online-count"
  to = "https://my-life-visitor-state.windking566.workers.dev/online-count"
  status = 200
  force = true

[[redirects]]
  from = "/visits"
  to = "https://my-life-visitor-state.windking566.workers.dev/visits"
  status = 200
  force = true

[[redirects]]
  from = "/admin-data"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-data"
  status = 200
  force = true

[[redirects]]
  from = "/admin-comments"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-comments"
  status = 200
  force = true

[[redirects]]
  from = "/admin-comments/:id"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-comments/:id"
  status = 200
  force = true

[[redirects]]
  from = "/admin-owner-ip-marks"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-owner-ip-marks"
  status = 200
  force = true

[[redirects]]
  from = "/admin-owner-ip-marks/:ipAddress"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-owner-ip-marks/:ipAddress"
  status = 200
  force = true

[[redirects]]
  from = "/admin-visits"
  to = "https://my-life-visitor-state.windking566.workers.dev/admin-visits"
  status = 200
  force = true
