name = "my-life-visitor-state"
main = "src/index.mjs"
compatibility_date = "2026-06-23"
workers_dev = true

[triggers]
crons = ["17 3 * * *"]

[[d1_databases]]
binding = "VISITOR_DB"
database_name = "my-life-visitor-state"
database_id = "8db207b2-f73b-46f3-bab6-f2acade0f434"
migrations_dir = "migrations"
